In [12]:
import numpy as np
from tkinter import *
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.animation import FuncAnimation
import math
import pandas as pd

marathon_2015_2017 = pd.read_csv('./material/marathon_2015_2017.csv')
record = pd.DataFrame(marathon_2015_2017, columns=['5K', '10K', '15K', '20K', 'Half', '25K', '30K',
                                                  '35K', '40K', 'Official Time']).sort_values(by=['Official Time'])
# DataFrame --> list
record_list = record.values.tolist()
xData = [5, 10, 15, 20, 21.098, 25, 30, 35, 40, 42.195]

C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [13]:
record.head()

        5K   10K   15K   20K  Half   25K   30K   35K   40K  Official Time
0      883  1783  2697  3629  3842  4567  5520  6479  7359           7757
53228  925  1828  2744  3675  3875  4619  5581  6499  7373           7777
1      883  1783  2698  3628  3841  4567  5519  6479  7362           7788
53229  924  1827  2744  3675  3875  4619  5581  6499  7394           7798
2      883  1783  2697  3629  3842  4567  5520  6479  7381           7822

In [14]:
record_list[0:5]

[[883, 1783, 2697, 3629, 3842, 4567, 5520, 6479, 7359, 7757],
 [925, 1828, 2744, 3675, 3875, 4619, 5581, 6499, 7373, 7777],
 [883, 1783, 2698, 3628, 3841, 4567, 5519, 6479, 7362, 7788],
 [924, 1827, 2744, 3675, 3875, 4619, 5581, 6499, 7394, 7798],
 [883, 1783, 2697, 3629, 3842, 4567, 5520, 6479, 7381, 7822]]

In [15]:
fig = Figure(figsize=(5,4), dpi=100)
ax = fig.add_subplot(111)
t_xdata, t_ydata = [], []
ax.set_xlim(0, 45)
ax.set_ylim(0, 10000)
dn = ax.plot([], [], 'ro')
t_a = 0

In [16]:
def seconds_to_hhmmss(seconds):
    hours = seconds // (60*60)
    seconds %= (60*60)
    minutes = seconds // 60
    seconds %= 60
    return '%02i:%02i:%02i' % (hours, minutes, seconds)

def init():
    ax.set_xlim(0, 45)
    ax.set_ylim(0, 10000)
    return dn

def animateFrame(frame):
    t_a = int(t_aSpbox.get()) -1
    t_x = xData[int(frame)]
    t_y = record_list[t_a][int(frame)]
    t_xdata.append(t_x)
    t_ydata.append(t_y)
    dn.set_data(t_xdata, t_ydata)
    return dn

def update():
    t_a = int(t_aSpbox.get()) -1
    ani = FuncAnimation(fig, animateFrame, frames=np.linspace(0, len(xData)-1, len(xData)),
                        init_func=init, blit=True)
    ax.set_xlabel('Distance(km)')
    ax.set_ylabel('Time(Second)')
    ax.set_title('Records of runner #' + str(t_a + 1))
    
    record_list_format = [seconds_to_hhmmss(s) for s in record_list[t_a]]
    for i, txt in enumerate(record_list_format):
        ax.annotate(txt, (xData[i], record_list[t_a][i]), fontsize=8)
   
    fig.canvas.draw()



# main
main = Tk()
main.title('Marathon Records')
main.geometry()

label = Label(main, text='Marathon Records')
label.config(font=('Courier', 18))
label.grid(row=0,column=0, columnspan=4)

t_aVal = DoubleVar(value=1.0)

t_aSpbox = Spinbox(main, textvariable=t_aVal, from_=0, to=len(record_list), increment=1,
                                                              justify=RIGHT)
t_aSpbox.config(state='readonly')
t_aSpbox.grid(row=1, column=1)
t_aLabel = Label(main, text='Rank of runner : ')
t_aLabel.grid(row=1, column=0)

Button(main, text='Run', width=20, height=3, command=lambda:update()).grid(row=1, column=2,
                                                                           columnspan=2, rowspan=1)
canvas = FigureCanvasTkAgg(fig, main)
canvas.get_tk_widget().grid(row=2, column=0, columnspan=3)

main.mainloop()

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\backends\_backend_tk.py", line 139, in _on_timer
    super()._on_timer()
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\backend_bases.py", line 1216, in _on_timer
    ret = func(*args, **kwargs)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\animation.py", line 1477, in _step
    still_going = super()._step(*args)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\animation.py", line 1189, in _step
    self._draw_next_frame(framedata, self._blit)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\animation.py", line 1208, in _draw_next_frame
    self._draw_frame(framedata)
  File "C:\Users\ysn65\anaconda3\envs\init_dn\lib\site-packages\matplotlib\animation.py", line 1776, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "<ipython-input-16-5f526a7106a6>", line 19, in animateFrame
    dn.set_data(t_xdata, t_ydata)
AttributeError: 'list' object has no attribute 'set_data'